### ISSUE TITLE
Error with 'path' parameter on Windows

### ISSUE THREAD

**Issue by alexmanie** [Azure/dotnet-template-azure-iot-edge-function#53]
Cannot create a new project based on aziotedgefunction on Windows.
Version: 

Error creating a new project:
![image](https://user-images.githubusercontent.com/8184686/127313070-67a3af89-2108-428b-bd9a-6f05ef0831bd.png)

Error trying to get --help by the package:
![image](https://user-images.githubusercontent.com/8184686/127313122-aacc83ee-ce76-4d33-8fb4-a65739810dec.png)

dotnet info:
`.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
`

![image](https://user-images.githubusercontent.com/8184686/127313205-dcb6fe59-7ae5-4e3e-9dff-2a05be756d71.png)

Template version: 3.5.1
![image](https://user-images.githubusercontent.com/8184686/127313804-d3f15945-e936-4edf-8f37-7ad8ad41fa32.png)

**Comment by cindydeng1998** [comment]
@alexmanie Thank you for reporting this issue and providing us with your repro steps. We have added this to our backlog.

**Comment by mhshami01** [comment]
Hello @alexmanie. We have released nuget v3.5.2 which fixes the reported issue. Thank you.
